In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
#linear regression models
from sklearn.linear_model import LinearRegression, Ridge, Lasso
#k-nearest neighbors regressor
from sklearn.neighbors import KNeighborsRegressor
#random forest regressor
from sklearn.ensemble import RandomForestRegressor
# evaluation metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, root_mean_squared_error, mean_absolute_error
#gradient boosting regressor
from sklearn.ensemble import GradientBoostingRegressor
# pipelines
from sklearn.pipeline import Pipeline
#scaling
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [2]:
df = pd.read_csv("formatted_gdp_growth_data.csv")
df.isna().sum()

year                                    0
gdp_growth(%)                           0
gdp_growth_lag1(%)                      1
gdp_growth_lag2(%)                      2
household_consumption(%)                0
unemployment_rate(%)                   11
under_earning_percentage(%)            13
inflation_rate(%)                       0
lending_interest_rate(%)_x              6
fdi_net_flows(US$)                      0
tax_revenue_percentage(%)              18
state_revenues_percentage(%)           18
gross_capital_formation_growth(%)_x     0
import_of_goods_and_services(US$)       0
export_of_goods_and_services(US$)       0
gross_capital_formation_growth(%)_y     0
exchange_rate(IDR/US$)                  0
dtype: int64

In [3]:
df.describe()

,year,gdp_growth(%),gdp_growth_lag1(%),gdp_growth_lag2(%),household_consumption(%),unemployment_rate(%),under_earning_percentage(%),inflation_rate(%),lending_interest_rate(%)_x,fdi_net_flows(US$),tax_revenue_percentage(%),state_revenues_percentage(%),gross_capital_formation_growth(%)_x,import_of_goods_and_services(US$),export_of_goods_and_services(US$),gross_capital_formation_growth(%)_y,exchange_rate(IDR/US$)
count,44.000000,44.000000,43.000000,42.000000,44.000000,33.00000,31.000000,44.000000,38.000000,4.400000e+01,26.000000,26.000000,44.000000,4.400000e+01,4.400000e+01,44.000000,44.000000
mean,2001.500000,4.955050,4.952864,4.944428,70.105728,5.06400,41.058065,8.753567,16.540965,7.589957e+09,15.860978,19.097463,24.451539,1.006864e+11,1.083679e+11,24.451539,7213.774407
std,12.845233,3.425071,3.465575,3.507137,4.371609,1.53784,25.570983,8.606848,5.683718,9.445301e+09,2.977557,2.298816,123.922857,8.409564e+10,8.827531e+10,123.922857,5086.558893
min,1980.000000,-13.126725,-13.126725,-13.126725,60.734725,2.61700,6.700000,1.560079,8.520000,-4.550355e+09,11.057787,15.108254,-164.509353,1.607649e+10,1.638707e+10,-164.509353,626.994000
25%,1990.750000,4.760247,4.740124,4.720001,67.084308,4.04900,19.800000,4.640005,12.017083,2.835000e+08,14.265207,17.412376,-9.587040,2.995771e+10,3.204349e+10,-9.587040,1923.441458
50%,2001.500000,5.240744,5.307197,5.337622,69.665130,4.61100,38.000000,6.586427,15.238750,3.227500e+09,15.516179,18.506774,5.652888,5.799963e+10,6.578898e+10,5.652888,8854.641667
75%,2012.250000,6.382869,6.420715,6.458562,72.436718,6.10600,64.000000,9.810600,20.765417,1.897614e+10,17.410716,20.653019,30.929111,1.728422e+11,1.834971e+11,30.929111,10407.763125
max,2023.000000,9.880078,9.880078,9.880078,81.334706,8.06000,86.800000,58.451041,32.154167,2.512073e+10,21.946434,25.474300,627.499564,2.765068e+11,3.232182e+11,627.499564,15236.884662

In [4]:
df[0:40]

,year,gdp_growth(%),gdp_growth_lag1(%),gdp_growth_lag2(%),household_consumption(%),unemployment_rate(%),under_earning_percentage(%),inflation_rate(%),lending_interest_rate(%)_x,fdi_net_flows(US$),tax_revenue_percentage(%),state_revenues_percentage(%),gross_capital_formation_growth(%)_x,import_of_goods_and_services(US$),export_of_goods_and_services(US$),gross_capital_formation_growth(%)_y,exchange_rate(IDR/US$)
0,1980,9.880078,NaN,NaN,70.834204,NaN,NaN,18.035422,NaN,1.800000e+08,21.779838,22.897656,24.369558,1.607649e+10,2.208839e+10,24.369558,626.994000
1,1981,7.927157,9.880078,NaN,76.531919,NaN,NaN,12.265908,NaN,1.330000e+08,21.946434,25.474300,12.398103,2.184722e+10,2.362907e+10,12.398103,631.756667
2,1982,2.246445,7.927157,9.880078,81.334706,NaN,NaN,9.445425,NaN,2.250000e+08,20.056144,21.489923,5.647824,2.370914e+10,2.017659e+10,5.647824,661.420750
3,1983,4.192967,2.246445,7.927157,71.666649,NaN,NaN,11.799738,NaN,2.920000e+08,18.822865,21.046818,627.499564,2.335427e+10,2.248829e+10,627.499564,909.264833
4,1984,6.975528,4.192967,2.246445,72.352702,NaN,86.2,10.455039,NaN,2.220000e+08,17.484389,21.508291,52.568955,1.934295e+10,2.317777e+10,52.568955,1025.944833
5,1985,2.462144,6.975528,4.192967,72.424958,NaN,NaN,4.724535,NaN,3.100000e+08,18.750897,21.481026,46.486894,1.786022e+10,2.027985e+10,46.486894,1110.580000
6,1986,5.875045,2.462144,6.975528,75.208760,NaN,NaN,5.822666,21.504167,2.580000e+08,14.620770,20.794591,-3.995642,1.640173e+10,1.638707e+10,-3.995642,1282.560000
7,1987,4.925927,5.875045,2.462144,71.411564,NaN,86.8,9.278654,21.666667,3.850000e+08,15.083695,19.853882,-18.896794,1.700630e+10,1.866107e+10,-18.896794,1643.848333
8,1988,5.780498,4.925927,5.875045,72.114454,NaN,NaN,8.045357,22.097500,5.760000e+08,15.083938,16.950870,-71.621388,1.872552e+10,2.111016e+10,-71.621388,1685.704167
9,1989,7.456587,5.780498,4.925927,69.343427,NaN,NaN,6.415541,21.699167,6.820000e+08,15.957202,17.401712,22.952061,2.171847e+10,2.464007e+10,22.952061,1770.059167
10,1990,7.242132,7.456587,5.780498,73.024205,NaN,78.6,7.819198,20.825000,1.093000e+09,19.137084,20.228306,103.268736,2.715728e+10,2.898253e+10,103.268736,1842.813333
11,1991,6.911983,7.242132,7.456587,73.359707,2.617,NaN,9.419068,25.533333,1.482000e+09,17.189697,18.648038,-33.202098,3.089119e+10,3.306381e+10,-33.202098,1950.317500
12,1992,6.497507,6.911983,7.242132,72.356220,2.734,NaN,7.523510,24.033333,1.777000e+09,17.122953,19.487503,13.744395,3.472088e+10,3.880173e+10,13.744395,2029.920833
13,1993,6.496408,6.497507,6.911983,67.535307,2.782,78.0,9.671911,20.586667,2.004000e+09,14.356420,17.077663,38.450762,3.755594e+10,4.227440e+10,38.450762,2087.103867
14,1994,7.539971,6.496408,6.497507,67.796950,4.366,NaN,8.531998,17.760000,2.109000e+09,15.948419,18.155527,36.400063,4.486988e+10,4.689663e+10,36.400063,2160.753675
15,1995,8.220007,7.539971,6.496408,69.406120,4.611,NaN,9.420303,18.851667,4.346000e+09,14.964772,17.691860,7.800788,5.588228e+10,5.318531e+10,7.800788,2248.607975
16,1996,7.818187,8.220007,7.539971,69.924141,4.861,68.1,7.973281,19.217500,6.194000e+09,14.234802,16.953516,-52.080132,6.011698e+10,5.871720e+10,-52.080132,2342.296292
17,1997,4.699879,7.818187,8.220007,68.524069,4.684,NaN,6.226152,21.817500,4.677000e+09,16.011848,18.137719,-25.772651,6.070015e+10,6.010604e+10,-25.772651,2909.380000
18,1998,-13.126725,4.699879,7.818187,73.474960,5.459,82.8,58.451041,32.154167,-2.408000e+08,15.027588,16.466714,-164.509353,4.124971e+10,5.055573e+10,-164.509353,10013.622500
19,1999,0.791126,-13.126725,4.699879,80.548254,6.358,66.2,20.477832,27.662500,-1.865621e+09,16.315836,18.059979,85.726670,3.840207e+10,4.972026e+10,85.726670,7855.150000
20,2000,4.920068,0.791126,-13.126725,68.182366,6.077,65.7,3.688620,18.455000,-4.550355e+09,NaN,NaN,49.332978,5.026469e+10,6.762117e+10,49.332978,8421.775000
21,2001,3.643466,4.920068,0.791126,70.039221,6.082,62.3,11.500116,18.547500,-2.977392e+09,11.578185,18.698703,29.105461,4.935520e+10,6.262588e+10,29.105461,10260.850000
22,2002,4.499475,3.643466,4.920068,74.879695,6.604,46.8,11.900120,18.945000,1.450855e+08,11.826960,17.444367,-79.354325,5.163844e+10,6.395680e+10,-79.354325,9311.191667
23,2003,4.780369,4.499475,3.643466,76.267506,6.657,45.5,6.757313,16.935000,-5.969238e+08,12.385532,17.323473,435.616000,5.432362e+10,7.155314e+10,435.616000,8577.133333
24,2004,5.030874,4.780369,4.499475,75.090350,7.303,45.4,6.064062,14.124167,1.896083e+09,12.330768,18.365509,-53.716777,7.074469e+10,8.274435e+10,-53.716777,8938.850000
25,2005,5.692571,5.030874,4.780369,72.471998,7.945,41.1,10.453200,14.050833,8.336257e+09,NaN,NaN,41.226522,8.553380e+10,9.738763e+10,41.226522,9704.741667
26,2006,5.500952,5.692571,5.030874,71.296226,7.551,46.8,13.108671,15.979167,4.914201e+09,NaN,NaN,-17.656484,9.341175e+10,1.131434e+11,-17.656484,9159.316667
27,2007,6.345022,5.500952,5.692571,71.889159,8.060,41.1,6.406561,13.861667,6.928480e+09,NaN,NaN,-137.635084,1.097551e+11,1.272261e+11,-137.635084,9141.000000
28,2008,6.013704,6.345022,5.500952,69.045034,7.208,38.0,10.226666,13.598333,9.318454e+09,13.310618,19.787844,-17.939593,1.467066e+11,1.520904e+11,-17.939593,9698.962500
29,2009,4.628871,6.013704,6.345022,68.291934,6.106,37.9,4.386413,14.498333,4.877369e+09,11.057787,15.108254,67.389372,1.152165e+11,1.303578e+11,67.389372,10389.937500
30,2010,6.223854,4.628871,6.013704,65.223091,5.614,34.1,5.134206,13.251667,1.529201e+10,NaN,NaN,-6.063093,1.691580e+11,1.834806e+11,-6.063093,9090.433333
31,2011,6.169784,6.223854,4.628871,64.482034,5.153,31.2,5.356048,12.403333,2.056494e+10,NaN,NaN,7.870459,2.129969e+11,2.350951e+11,7.870459,8770.433333
32,2012,6.030051,6.169784,6.223854,65.638035,4.468,26.6,4.279514,11.795000,2.120078e+10,NaN,NaN,10.981235,2.293621e+11,2.257444e+11,10.981235,9386.629167
33,2013,5.557264,6.030051,6.169784,66.347182,4.336,27.2,6.412495,11.657500,2.328174e+10,NaN,NaN,2.846751,2.255194e+11,2.183084e+11,2.846751,10461.240000
34,2014,5.006668,5.557264,6.030051,66.564142,4.049,25.7,6.394929,12.605000,2.512073e+10,NaN,NaN,5.657952,2.174852e+11,2.108201e+11,5.657952,11865.211296
35,2015,4.876322,5.006668,5.557264,67.199432,4.514,21.6,6.363121,12.662500,1.977913e+10,NaN,NaN,3.002346,1.788637e+11,1.821583e+11,3.002346,13389.412937
36,2016,5.033069,4.876322,5.006668,67.354611,4.301,18.0,3.525805,11.888333,4.541714e+09,NaN,NaN,4.985806,1.708350e+11,1.778860e+11,4.985806,13308.326802
37,2017,5.069786,5.033069,4.876322,66.396144,3.783,14.8,3.808799,11.073333,2.051031e+10,NaN,NaN,5.690161,1.947773e+11,2.049245e+11,5.690161,13380.833879
38,2018,5.174292,5.069786,5.033069,66.001127,4.387,12.5,3.198348,10.536667,1.890983e+10,NaN,NaN,8.523941,2.300456e+11,2.189056e+11,8.523941,14236.938773
39,2019,5.019288,5.174292,5.069786,66.738936,3.590,10.8,3.030585,10.365833,2.499355e+10,NaN,NaN,2.359847,2.130346e+11,2.080578e+11,2.359847,14147.671361

In [5]:
# impute gdp_growth lag 1 and 2 with linear regression
x = df[["fdi_net_flows(US$)","gross_capital_formation_growth(%)_y", "exchange_rate(IDR/US$)"]]
x = x.iloc[1:40]

y = df["gdp_growth_lag1(%)"]
y = y.iloc[1:40]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

model_impute_lag1 = Lasso(alpha=0.1)
model_impute_lag1.fit(x_train, y_train)

Lasso(alpha=0.1)

In [6]:
# test the model performance on the test set
np.random.seed(42)
y_pred = model_impute_lag1.predict(x_test)

performance = {
    "MSE": mean_squared_error(y_test, y_pred),
    "MAE": mean_absolute_error(y_test, y_pred),
    "R2": r2_score(y_test, y_pred),
    "RMSE" : root_mean_squared_error(y_test, y_pred)
}

print(performance)

{'MSE': 4.927428540573947, 'MAE': 1.7992104514695815, 'R2': -2.1201289271728343, 'RMSE': 2.21978119204888}

In [7]:
# use the model to predict the lag1 missing value
missing_lag1 = df[df["gdp_growth_lag1(%)"].isna()]
missing_lag1_x = missing_lag1[["fdi_net_flows(US$)","gross_capital_formation_growth(%)_y", "exchange_rate(IDR/US$)"]]
predicted_lag1 = model_impute_lag1.predict(missing_lag1_x)
df.loc[df["gdp_growth_lag1(%)"].isna(), "gdp_growth_lag1(%)"] = predicted_lag1

In [8]:
df.head()

,year,gdp_growth(%),gdp_growth_lag1(%),gdp_growth_lag2(%),household_consumption(%),unemployment_rate(%),under_earning_percentage(%),inflation_rate(%),lending_interest_rate(%)_x,fdi_net_flows(US$),tax_revenue_percentage(%),state_revenues_percentage(%),gross_capital_formation_growth(%)_x,import_of_goods_and_services(US$),export_of_goods_and_services(US$),gross_capital_formation_growth(%)_y,exchange_rate(IDR/US$)
0,1980,9.880078,6.735124,NaN,70.834204,NaN,NaN,18.035422,NaN,180000000.0,21.779838,22.897656,24.369558,1.607649e+10,2.208839e+10,24.369558,626.994000
1,1981,7.927157,9.880078,NaN,76.531919,NaN,NaN,12.265908,NaN,133000000.0,21.946434,25.474300,12.398103,2.184722e+10,2.362907e+10,12.398103,631.756667
2,1982,2.246445,7.927157,9.880078,81.334706,NaN,NaN,9.445425,NaN,225000000.0,20.056144,21.489923,5.647824,2.370914e+10,2.017659e+10,5.647824,661.420750
3,1983,4.192967,2.246445,7.927157,71.666649,NaN,NaN,11.799738,NaN,292000000.0,18.822865,21.046818,627.499564,2.335427e+10,2.248829e+10,627.499564,909.264833
4,1984,6.975528,4.192967,2.246445,72.352702,NaN,86.2,10.455039,NaN,222000000.0,17.484389,21.508291,52.568955,1.934295e+10,2.317777e+10,52.568955,1025.944833

# Impute lag_2 with Lasso

In [9]:
x = df[["fdi_net_flows(US$)","gross_capital_formation_growth(%)_y", "exchange_rate(IDR/US$)"]]
x = x.iloc[2:40]

y = df["gdp_growth_lag2(%)"]
y = y.iloc[2:40]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

# create a pipeline for the model with normalization and lasso regression       
pipeline = Pipeline([
    ("normalization", MinMaxScaler()),
    ("model", Ridge(alpha=0.1))
])
pipeline.fit(x_train, y_train)

Pipeline(steps=[('normalization', MinMaxScaler()), ('model', Ridge(alpha=0.1))])

In [10]:
# evaluate the model performance on the test set
y_pred = pipeline.predict(x_test)
performance = {
    "MSE": mean_squared_error(y_test, y_pred),
    "MAE": mean_absolute_error(y_test, y_pred),
    "R2": r2_score(y_test, y_pred),
    "RMSE" : root_mean_squared_error(y_test, y_pred)
}
print(performance)

{'MSE': 1.5936181716843048, 'MAE': 0.874695886106394, 'R2': -3.6144120784447518, 'RMSE': 1.2623859044223777}

In [11]:
# use the model to impute the missing values in gdp_growth_lag2

missing_lag2 = df[df["gdp_growth_lag2(%)"].isna()]
missing_lag2_x = missing_lag2[["fdi_net_flows(US$)","gross_capital_formation_growth(%)_y", "exchange_rate(IDR/US$)"]]
predicted_lag2 = pipeline.predict(missing_lag2_x)
df.loc[df["gdp_growth_lag2(%)"].isna(), "gdp_growth_lag2(%)"] = predicted_lag2

In [12]:

# fix lag 1
df["gdp_growth_lag1(%)"].iloc[0] = df["gdp_growth_lag2(%)"].iloc[1]
df.head()

/var/folders/tk/mn4_r_cn03ndtjss8b670dfw0000gn/T/ipykernel_4406/2192646626.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["gdp_growth_lag1(%)"].iloc[0] = df["gdp_growth_lag2(%)"].iloc[1]
/var/folders/tk/mn4_r_cn03ndtjss8b670dfw0000gn/T/ipykernel_4406/2192646626.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["gdp_growth_lag1(%)"].iloc[0] = df["gdp_growth_lag2(%)"].iloc[1]

,year,gdp_growth(%),gdp_growth_lag1(%),gdp_growth_lag2(%),household_consumption(%),unemployment_rate(%),under_earning_percentage(%),inflation_rate(%),lending_interest_rate(%)_x,fdi_net_flows(US$),tax_revenue_percentage(%),state_revenues_percentage(%),gross_capital_formation_growth(%)_x,import_of_goods_and_services(US$),export_of_goods_and_services(US$),gross_capital_formation_growth(%)_y,exchange_rate(IDR/US$)
0,1980,9.880078,6.165775,6.163400,70.834204,NaN,NaN,18.035422,NaN,180000000.0,21.779838,22.897656,24.369558,1.607649e+10,2.208839e+10,24.369558,626.994000
1,1981,7.927157,9.880078,6.165775,76.531919,NaN,NaN,12.265908,NaN,133000000.0,21.946434,25.474300,12.398103,2.184722e+10,2.362907e+10,12.398103,631.756667
2,1982,2.246445,7.927157,9.880078,81.334706,NaN,NaN,9.445425,NaN,225000000.0,20.056144,21.489923,5.647824,2.370914e+10,2.017659e+10,5.647824,661.420750
3,1983,4.192967,2.246445,7.927157,71.666649,NaN,NaN,11.799738,NaN,292000000.0,18.822865,21.046818,627.499564,2.335427e+10,2.248829e+10,627.499564,909.264833
4,1984,6.975528,4.192967,2.246445,72.352702,NaN,86.2,10.455039,NaN,222000000.0,17.484389,21.508291,52.568955,1.934295e+10,2.317777e+10,52.568955,1025.944833

# Impute Unemployment Rate with Regression model

In [13]:
# split data
x = df[["gdp_growth_lag1(%)", "gdp_growth_lag2(%)"]]
x = x.iloc[18:40]

y = df["unemployment_rate(%)"]
y = y.iloc[18:40]

# train test split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# experiment models  
models = {
    "LinearRegression": LinearRegression(),
    "Ridge": Ridge(alpha=0.1),
    "Lasso": Lasso(alpha=0.1),
}

performance = {
    "MAE" : [],
    "MSE" : [], 
    "RMSE" : [],
    "R2" : []
}

for name, model in models.items():
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)
    performance["MAE"].append(mean_absolute_error(y_test, y_pred))
    performance["MSE"].append(mean_squared_error(y_test, y_pred))
    performance["RMSE"].append(root_mean_squared_error(y_test, y_pred))
    performance["R2"].append(r2_score(y_test, y_pred))

    # format into pandas data
performance_df = pd.DataFrame(performance, index=models.keys())
print(performance_df)

                       MAE       MSE      RMSE        R2
LinearRegression  1.030005  1.479729  1.216441 -0.222621
Ridge             1.027041  1.471568  1.213082 -0.215878
Lasso             0.899254  1.199115  1.095041  0.009235

In [14]:
# impute the missing values in the unemployment_rate column with the best model (Lasso)
np.random.seed(42)
Lasso_model_ = Lasso(alpha=0.1)
Lasso_model_.fit(x_train, y_train)
x_imputed = df[df["unemployment_rate(%)"].isna()][["gdp_growth_lag1(%)", "gdp_growth_lag2(%)"]]
y_pred_imputed = Lasso_model_.predict(x_imputed)
df.loc[df["unemployment_rate(%)"].isna(), "unemployment_rate(%)"] = y_pred_imputed

# Under-erning percentage

In [15]:
np.random.seed(42)
# split data
x = df[["gdp_growth_lag1(%)", "gdp_growth_lag2(%)", "unemployment_rate(%)", 
        "inflation_rate(%)", "exchange_rate(IDR/US$)", "household_consumption(%)"]]
x = x.iloc[18:40]

y = df["under_earning_percentage(%)"]
y = y.iloc[18:40]

# train test split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# experiment models  
models = {
    "LinearRegression": LinearRegression(),
    "Ridge": Ridge(alpha=0.1),
    "Lasso": Lasso(alpha=0.1),
}

performance = {
    "MAE" : [],
    "MSE" : [], 
    "RMSE" : [],
    "R2" : []
}

for name, model in models.items():
    moodel = Pipeline([
        ("normalization", StandardScaler()),
        ("model", model)
    ])
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)
    performance["MAE"].append(mean_absolute_error(y_test, y_pred))
    performance["MSE"].append(mean_squared_error(y_test, y_pred))
    performance["RMSE"].append(root_mean_squared_error(y_test, y_pred))
    performance["R2"].append(r2_score(y_test, y_pred))

# format into pandas data frame
performance_df = pd.DataFrame(performance, index=models.keys())
print(performance_df)

                        MAE         MSE       RMSE        R2
LinearRegression  16.924452  472.636245  21.740199 -0.065325
Ridge             16.706921  459.770745  21.442265 -0.036326
Lasso             15.470655  395.657492  19.891141  0.108185

In [16]:
# impute the missing values in the unemployment_rate column with the best model (Lasso)
np.random.seed(42)
lasso_model = Lasso(alpha=0.1)
lasso_model.fit(x_train, y_train)
x_imputed = df[df["under_earning_percentage(%)"].isna()][["gdp_growth_lag1(%)", "gdp_growth_lag2(%)", "unemployment_rate(%)", 
        "inflation_rate(%)", "exchange_rate(IDR/US$)", "household_consumption(%)"]]
y_pred_imputed = lasso_model.predict(x_imputed)
df.loc[df["under_earning_percentage(%)"].isna(), "under_earning_percentage(%)"] = y_pred_imputed

In [17]:
df[0:45]

,year,gdp_growth(%),gdp_growth_lag1(%),gdp_growth_lag2(%),household_consumption(%),unemployment_rate(%),under_earning_percentage(%),inflation_rate(%),lending_interest_rate(%)_x,fdi_net_flows(US$),tax_revenue_percentage(%),state_revenues_percentage(%),gross_capital_formation_growth(%)_x,import_of_goods_and_services(US$),export_of_goods_and_services(US$),gross_capital_formation_growth(%)_y,exchange_rate(IDR/US$)
0,1980,9.880078,6.165775,6.163400,70.834204,5.620902,89.164321,18.035422,NaN,1.800000e+08,21.779838,22.897656,24.369558,1.607649e+10,2.208839e+10,24.369558,626.994000
1,1981,7.927157,9.880078,6.165775,76.531919,5.620827,88.921829,12.265908,NaN,1.330000e+08,21.946434,25.474300,12.398103,2.184722e+10,2.362907e+10,12.398103,631.756667
2,1982,2.246445,7.927157,9.880078,81.334706,5.504006,75.150527,9.445425,NaN,2.250000e+08,20.056144,21.489923,5.647824,2.370914e+10,2.017659e+10,5.647824,661.420750
3,1983,4.192967,2.246445,7.927157,71.666649,5.565429,67.419547,11.799738,NaN,2.920000e+08,18.822865,21.046818,627.499564,2.335427e+10,2.248829e+10,627.499564,909.264833
4,1984,6.975528,4.192967,2.246445,72.352702,5.744096,86.200000,10.455039,NaN,2.220000e+08,17.484389,21.508291,52.568955,1.934295e+10,2.317777e+10,52.568955,1025.944833
5,1985,2.462144,6.975528,4.192967,72.424958,5.682875,71.527427,4.724535,NaN,3.100000e+08,18.750897,21.481026,46.486894,1.786022e+10,2.027985e+10,46.486894,1110.580000
6,1986,5.875045,2.462144,6.975528,75.208760,5.595359,60.273201,5.822666,21.504167,2.580000e+08,14.620770,20.794591,-3.995642,1.640173e+10,1.638707e+10,-3.995642,1282.560000
7,1987,4.925927,5.875045,2.462144,71.411564,5.737312,86.800000,9.278654,21.666667,3.850000e+08,15.083695,19.853882,-18.896794,1.700630e+10,1.866107e+10,-18.896794,1643.848333
8,1988,5.780498,4.925927,5.875045,72.114454,5.629971,67.660828,8.045357,22.097500,5.760000e+08,15.083938,16.950870,-71.621388,1.872552e+10,2.111016e+10,-71.621388,1685.704167
9,1989,7.456587,5.780498,4.925927,69.343427,5.659822,66.733250,6.415541,21.699167,6.820000e+08,15.957202,17.401712,22.952061,2.171847e+10,2.464007e+10,22.952061,1770.059167
10,1990,7.242132,7.456587,5.780498,73.024205,5.632945,78.600000,7.819198,20.825000,1.093000e+09,19.137084,20.228306,103.268736,2.715728e+10,2.898253e+10,103.268736,1842.813333
11,1991,6.911983,7.242132,7.456587,73.359707,2.617000,69.433190,9.419068,25.533333,1.482000e+09,17.189697,18.648038,-33.202098,3.089119e+10,3.306381e+10,-33.202098,1950.317500
12,1992,6.497507,6.911983,7.242132,72.356220,2.734000,65.358433,7.523510,24.033333,1.777000e+09,17.122953,19.487503,13.744395,3.472088e+10,3.880173e+10,13.744395,2029.920833
13,1993,6.496408,6.497507,6.911983,67.535307,2.782000,78.000000,9.671911,20.586667,2.004000e+09,14.356420,17.077663,38.450762,3.755594e+10,4.227440e+10,38.450762,2087.103867
14,1994,7.539971,6.496408,6.497507,67.796950,4.366000,65.597060,8.531998,17.760000,2.109000e+09,15.948419,18.155527,36.400063,4.486988e+10,4.689663e+10,36.400063,2160.753675
15,1995,8.220007,7.539971,6.496408,69.406120,4.611000,69.515793,9.420303,18.851667,4.346000e+09,14.964772,17.691860,7.800788,5.588228e+10,5.318531e+10,7.800788,2248.607975
16,1996,7.818187,8.220007,7.539971,69.924141,4.861000,68.100000,7.973281,19.217500,6.194000e+09,14.234802,16.953516,-52.080132,6.011698e+10,5.871720e+10,-52.080132,2342.296292
17,1997,4.699879,7.818187,8.220007,68.524069,4.684000,58.154335,6.226152,21.817500,4.677000e+09,16.011848,18.137719,-25.772651,6.070015e+10,6.010604e+10,-25.772651,2909.380000
18,1998,-13.126725,4.699879,7.818187,73.474960,5.459000,82.800000,58.451041,32.154167,-2.408000e+08,15.027588,16.466714,-164.509353,4.124971e+10,5.055573e+10,-164.509353,10013.622500
19,1999,0.791126,-13.126725,4.699879,80.548254,6.358000,66.200000,20.477832,27.662500,-1.865621e+09,16.315836,18.059979,85.726670,3.840207e+10,4.972026e+10,85.726670,7855.150000
20,2000,4.920068,0.791126,-13.126725,68.182366,6.077000,65.700000,3.688620,18.455000,-4.550355e+09,NaN,NaN,49.332978,5.026469e+10,6.762117e+10,49.332978,8421.775000
21,2001,3.643466,4.920068,0.791126,70.039221,6.082000,62.300000,11.500116,18.547500,-2.977392e+09,11.578185,18.698703,29.105461,4.935520e+10,6.262588e+10,29.105461,10260.850000
22,2002,4.499475,3.643466,4.920068,74.879695,6.604000,46.800000,11.900120,18.945000,1.450855e+08,11.826960,17.444367,-79.354325,5.163844e+10,6.395680e+10,-79.354325,9311.191667
23,2003,4.780369,4.499475,3.643466,76.267506,6.657000,45.500000,6.757313,16.935000,-5.969238e+08,12.385532,17.323473,435.616000,5.432362e+10,7.155314e+10,435.616000,8577.133333
24,2004,5.030874,4.780369,4.499475,75.090350,7.303000,45.400000,6.064062,14.124167,1.896083e+09,12.330768,18.365509,-53.716777,7.074469e+10,8.274435e+10,-53.716777,8938.850000
25,2005,5.692571,5.030874,4.780369,72.471998,7.945000,41.100000,10.453200,14.050833,8.336257e+09,NaN,NaN,41.226522,8.553380e+10,9.738763e+10,41.226522,9704.741667
26,2006,5.500952,5.692571,5.030874,71.296226,7.551000,46.800000,13.108671,15.979167,4.914201e+09,NaN,NaN,-17.656484,9.341175e+10,1.131434e+11,-17.656484,9159.316667
27,2007,6.345022,5.500952,5.692571,71.889159,8.060000,41.100000,6.406561,13.861667,6.928480e+09,NaN,NaN,-137.635084,1.097551e+11,1.272261e+11,-137.635084,9141.000000
28,2008,6.013704,6.345022,5.500952,69.045034,7.208000,38.000000,10.226666,13.598333,9.318454e+09,13.310618,19.787844,-17.939593,1.467066e+11,1.520904e+11,-17.939593,9698.962500
29,2009,4.628871,6.013704,6.345022,68.291934,6.106000,37.900000,4.386413,14.498333,4.877369e+09,11.057787,15.108254,67.389372,1.152165e+11,1.303578e+11,67.389372,10389.937500
30,2010,6.223854,4.628871,6.013704,65.223091,5.614000,34.100000,5.134206,13.251667,1.529201e+10,NaN,NaN,-6.063093,1.691580e+11,1.834806e+11,-6.063093,9090.433333
31,2011,6.169784,6.223854,4.628871,64.482034,5.153000,31.200000,5.356048,12.403333,2.056494e+10,NaN,NaN,7.870459,2.129969e+11,2.350951e+11,7.870459,8770.433333
32,2012,6.030051,6.169784,6.223854,65.638035,4.468000,26.600000,4.279514,11.795000,2.120078e+10,NaN,NaN,10.981235,2.293621e+11,2.257444e+11,10.981235,9386.629167
33,2013,5.557264,6.030051,6.169784,66.347182,4.336000,27.200000,6.412495,11.657500,2.328174e+10,NaN,NaN,2.846751,2.255194e+11,2.183084e+11,2.846751,10461.240000
34,2014,5.006668,5.557264,6.030051,66.564142,4.049000,25.700000,6.394929,12.605000,2.512073e+10,NaN,NaN,5.657952,2.174852e+11,2.108201e+11,5.657952,11865.211296
35,2015,4.876322,5.006668,5.557264,67.199432,4.514000,21.600000,6.363121,12.662500,1.977913e+10,NaN,NaN,3.002346,1.788637e+11,1.821583e+11,3.002346,13389.412937
36,2016,5.033069,4.876322,5.006668,67.354611,4.301000,18.000000,3.525805,11.888333,4.541714e+09,NaN,NaN,4.985806,1.708350e+11,1.778860e+11,4.985806,13308.326802
37,2017,5.069786,5.033069,4.876322,66.396144,3.783000,14.800000,3.808799,11.073333,2.051031e+10,NaN,NaN,5.690161,1.947773e+11,2.049245e+11,5.690161,13380.833879
38,2018,5.174292,5.069786,5.033069,66.001127,4.387000,12.500000,3.198348,10.536667,1.890983e+10,NaN,NaN,8.523941,2.300456e+11,2.189056e+11,8.523941,14236.938773
39,2019,5.019288,5.174292,5.069786,66.738936,3.590000,10.800000,3.030585,10.365833,2.499355e+10,NaN,NaN,2.359847,2.130346e+11,2.080578e+11,2.359847,14147.671361
40,2020,-2.065512,5.019288,5.174292,68.589643,4.255000,9.800000,1.919835,9.544167,1.917508e+10,NaN,NaN,-6.897226,1.656468e+11,1.835466e+11,-6.897226,14582.203468
41,2021,3.702886,-2.065512,5.019288,64.875755,3.827000,8.600000,1.560079,8.922500,2.121308e+10,NaN,NaN,4.074672,2.229238e+11,2.541095e+11,4.074672,14308.143901
42,2022,5.307197,3.702886,-2.065512,60.734725,3.462000,7.900000,4.209465,8.520000,2.470203e+10,NaN,NaN,4.025415,2.765068e+11,3.232182e+11,4.025415,14849.853936
43,2023,5.049023,5.307197,3.702886,61.880414,3.308000,6.700000,3.669387,8.926667,2.154336e+10,NaN,NaN,5.205074,2.685084e+11,2.982821e+11,5.205074,15236.884662

# Interpolate Tax Revenue

In [18]:
# impute the missing values in tax_revenue_percentage with linear interpolation
df["tax_revenue_percentage(%)"].iloc[0:30] = df["tax_revenue_percentage(%)"].iloc[0:30].interpolate(method="linear")
df[0:45]

/var/folders/tk/mn4_r_cn03ndtjss8b670dfw0000gn/T/ipykernel_4406/1948936870.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["tax_revenue_percentage(%)"].iloc[0:30] = df["tax_revenue_percentage(%)"].iloc[0:30].interpolate(method="linear")
/var/folders/tk/mn4_r_cn03ndtjss8b670dfw0000gn/T/ipykernel_4406/1948936870.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["tax_revenue_percentage(%)"].iloc[0:30] = df["tax_revenue_percentage(%)"].iloc[0:30].interpolate(method="linear")

,year,gdp_growth(%),gdp_growth_lag1(%),gdp_growth_lag2(%),household_consumption(%),unemployment_rate(%),under_earning_percentage(%),inflation_rate(%),lending_interest_rate(%)_x,fdi_net_flows(US$),tax_revenue_percentage(%),state_revenues_percentage(%),gross_capital_formation_growth(%)_x,import_of_goods_and_services(US$),export_of_goods_and_services(US$),gross_capital_formation_growth(%)_y,exchange_rate(IDR/US$)
0,1980,9.880078,6.165775,6.163400,70.834204,5.620902,89.164321,18.035422,NaN,1.800000e+08,21.779838,22.897656,24.369558,1.607649e+10,2.208839e+10,24.369558,626.994000
1,1981,7.927157,9.880078,6.165775,76.531919,5.620827,88.921829,12.265908,NaN,1.330000e+08,21.946434,25.474300,12.398103,2.184722e+10,2.362907e+10,12.398103,631.756667
2,1982,2.246445,7.927157,9.880078,81.334706,5.504006,75.150527,9.445425,NaN,2.250000e+08,20.056144,21.489923,5.647824,2.370914e+10,2.017659e+10,5.647824,661.420750
3,1983,4.192967,2.246445,7.927157,71.666649,5.565429,67.419547,11.799738,NaN,2.920000e+08,18.822865,21.046818,627.499564,2.335427e+10,2.248829e+10,627.499564,909.264833
4,1984,6.975528,4.192967,2.246445,72.352702,5.744096,86.200000,10.455039,NaN,2.220000e+08,17.484389,21.508291,52.568955,1.934295e+10,2.317777e+10,52.568955,1025.944833
5,1985,2.462144,6.975528,4.192967,72.424958,5.682875,71.527427,4.724535,NaN,3.100000e+08,18.750897,21.481026,46.486894,1.786022e+10,2.027985e+10,46.486894,1110.580000
6,1986,5.875045,2.462144,6.975528,75.208760,5.595359,60.273201,5.822666,21.504167,2.580000e+08,14.620770,20.794591,-3.995642,1.640173e+10,1.638707e+10,-3.995642,1282.560000
7,1987,4.925927,5.875045,2.462144,71.411564,5.737312,86.800000,9.278654,21.666667,3.850000e+08,15.083695,19.853882,-18.896794,1.700630e+10,1.866107e+10,-18.896794,1643.848333
8,1988,5.780498,4.925927,5.875045,72.114454,5.629971,67.660828,8.045357,22.097500,5.760000e+08,15.083938,16.950870,-71.621388,1.872552e+10,2.111016e+10,-71.621388,1685.704167
9,1989,7.456587,5.780498,4.925927,69.343427,5.659822,66.733250,6.415541,21.699167,6.820000e+08,15.957202,17.401712,22.952061,2.171847e+10,2.464007e+10,22.952061,1770.059167
10,1990,7.242132,7.456587,5.780498,73.024205,5.632945,78.600000,7.819198,20.825000,1.093000e+09,19.137084,20.228306,103.268736,2.715728e+10,2.898253e+10,103.268736,1842.813333
11,1991,6.911983,7.242132,7.456587,73.359707,2.617000,69.433190,9.419068,25.533333,1.482000e+09,17.189697,18.648038,-33.202098,3.089119e+10,3.306381e+10,-33.202098,1950.317500
12,1992,6.497507,6.911983,7.242132,72.356220,2.734000,65.358433,7.523510,24.033333,1.777000e+09,17.122953,19.487503,13.744395,3.472088e+10,3.880173e+10,13.744395,2029.920833
13,1993,6.496408,6.497507,6.911983,67.535307,2.782000,78.000000,9.671911,20.586667,2.004000e+09,14.356420,17.077663,38.450762,3.755594e+10,4.227440e+10,38.450762,2087.103867
14,1994,7.539971,6.496408,6.497507,67.796950,4.366000,65.597060,8.531998,17.760000,2.109000e+09,15.948419,18.155527,36.400063,4.486988e+10,4.689663e+10,36.400063,2160.753675
15,1995,8.220007,7.539971,6.496408,69.406120,4.611000,69.515793,9.420303,18.851667,4.346000e+09,14.964772,17.691860,7.800788,5.588228e+10,5.318531e+10,7.800788,2248.607975
16,1996,7.818187,8.220007,7.539971,69.924141,4.861000,68.100000,7.973281,19.217500,6.194000e+09,14.234802,16.953516,-52.080132,6.011698e+10,5.871720e+10,-52.080132,2342.296292
17,1997,4.699879,7.818187,8.220007,68.524069,4.684000,58.154335,6.226152,21.817500,4.677000e+09,16.011848,18.137719,-25.772651,6.070015e+10,6.010604e+10,-25.772651,2909.380000
18,1998,-13.126725,4.699879,7.818187,73.474960,5.459000,82.800000,58.451041,32.154167,-2.408000e+08,15.027588,16.466714,-164.509353,4.124971e+10,5.055573e+10,-164.509353,10013.622500
19,1999,0.791126,-13.126725,4.699879,80.548254,6.358000,66.200000,20.477832,27.662500,-1.865621e+09,16.315836,18.059979,85.726670,3.840207e+10,4.972026e+10,85.726670,7855.150000
20,2000,4.920068,0.791126,-13.126725,68.182366,6.077000,65.700000,3.688620,18.455000,-4.550355e+09,13.947010,NaN,49.332978,5.026469e+10,6.762117e+10,49.332978,8421.775000
21,2001,3.643466,4.920068,0.791126,70.039221,6.082000,62.300000,11.500116,18.547500,-2.977392e+09,11.578185,18.698703,29.105461,4.935520e+10,6.262588e+10,29.105461,10260.850000
22,2002,4.499475,3.643466,4.920068,74.879695,6.604000,46.800000,11.900120,18.945000,1.450855e+08,11.826960,17.444367,-79.354325,5.163844e+10,6.395680e+10,-79.354325,9311.191667
23,2003,4.780369,4.499475,3.643466,76.267506,6.657000,45.500000,6.757313,16.935000,-5.969238e+08,12.385532,17.323473,435.616000,5.432362e+10,7.155314e+10,435.616000,8577.133333
24,2004,5.030874,4.780369,4.499475,75.090350,7.303000,45.400000,6.064062,14.124167,1.896083e+09,12.330768,18.365509,-53.716777,7.074469e+10,8.274435e+10,-53.716777,8938.850000
25,2005,5.692571,5.030874,4.780369,72.471998,7.945000,41.100000,10.453200,14.050833,8.336257e+09,12.575730,NaN,41.226522,8.553380e+10,9.738763e+10,41.226522,9704.741667
26,2006,5.500952,5.692571,5.030874,71.296226,7.551000,46.800000,13.108671,15.979167,4.914201e+09,12.820693,NaN,-17.656484,9.341175e+10,1.131434e+11,-17.656484,9159.316667
27,2007,6.345022,5.500952,5.692571,71.889159,8.060000,41.100000,6.406561,13.861667,6.928480e+09,13.065655,NaN,-137.635084,1.097551e+11,1.272261e+11,-137.635084,9141.000000
28,2008,6.013704,6.345022,5.500952,69.045034,7.208000,38.000000,10.226666,13.598333,9.318454e+09,13.310618,19.787844,-17.939593,1.467066e+11,1.520904e+11,-17.939593,9698.962500
29,2009,4.628871,6.013704,6.345022,68.291934,6.106000,37.900000,4.386413,14.498333,4.877369e+09,11.057787,15.108254,67.389372,1.152165e+11,1.303578e+11,67.389372,10389.937500
30,2010,6.223854,4.628871,6.013704,65.223091,5.614000,34.100000,5.134206,13.251667,1.529201e+10,NaN,NaN,-6.063093,1.691580e+11,1.834806e+11,-6.063093,9090.433333
31,2011,6.169784,6.223854,4.628871,64.482034,5.153000,31.200000,5.356048,12.403333,2.056494e+10,NaN,NaN,7.870459,2.129969e+11,2.350951e+11,7.870459,8770.433333
32,2012,6.030051,6.169784,6.223854,65.638035,4.468000,26.600000,4.279514,11.795000,2.120078e+10,NaN,NaN,10.981235,2.293621e+11,2.257444e+11,10.981235,9386.629167
33,2013,5.557264,6.030051,6.169784,66.347182,4.336000,27.200000,6.412495,11.657500,2.328174e+10,NaN,NaN,2.846751,2.255194e+11,2.183084e+11,2.846751,10461.240000
34,2014,5.006668,5.557264,6.030051,66.564142,4.049000,25.700000,6.394929,12.605000,2.512073e+10,NaN,NaN,5.657952,2.174852e+11,2.108201e+11,5.657952,11865.211296
35,2015,4.876322,5.006668,5.557264,67.199432,4.514000,21.600000,6.363121,12.662500,1.977913e+10,NaN,NaN,3.002346,1.788637e+11,1.821583e+11,3.002346,13389.412937
36,2016,5.033069,4.876322,5.006668,67.354611,4.301000,18.000000,3.525805,11.888333,4.541714e+09,NaN,NaN,4.985806,1.708350e+11,1.778860e+11,4.985806,13308.326802
37,2017,5.069786,5.033069,4.876322,66.396144,3.783000,14.800000,3.808799,11.073333,2.051031e+10,NaN,NaN,5.690161,1.947773e+11,2.049245e+11,5.690161,13380.833879
38,2018,5.174292,5.069786,5.033069,66.001127,4.387000,12.500000,3.198348,10.536667,1.890983e+10,NaN,NaN,8.523941,2.300456e+11,2.189056e+11,8.523941,14236.938773
39,2019,5.019288,5.174292,5.069786,66.738936,3.590000,10.800000,3.030585,10.365833,2.499355e+10,NaN,NaN,2.359847,2.130346e+11,2.080578e+11,2.359847,14147.671361
40,2020,-2.065512,5.019288,5.174292,68.589643,4.255000,9.800000,1.919835,9.544167,1.917508e+10,NaN,NaN,-6.897226,1.656468e+11,1.835466e+11,-6.897226,14582.203468
41,2021,3.702886,-2.065512,5.019288,64.875755,3.827000,8.600000,1.560079,8.922500,2.121308e+10,NaN,NaN,4.074672,2.229238e+11,2.541095e+11,4.074672,14308.143901
42,2022,5.307197,3.702886,-2.065512,60.734725,3.462000,7.900000,4.209465,8.520000,2.470203e+10,NaN,NaN,4.025415,2.765068e+11,3.232182e+11,4.025415,14849.853936
43,2023,5.049023,5.307197,3.702886,61.880414,3.308000,6.700000,3.669387,8.926667,2.154336e+10,NaN,NaN,5.205074,2.685084e+11,2.982821e+11,5.205074,15236.884662

# Fill Tax Revenue[30:44] missing value with regression model

In [19]:
# split data
x = df[["gdp_growth(%)", "unemployment_rate(%)", 
        "inflation_rate(%)", "exchange_rate(IDR/US$)", "household_consumption(%)", "under_earning_percentage(%)"]]
x = x.iloc[0:30]

y = df["tax_revenue_percentage(%)"]
y = y.iloc[0:30]

# train test split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.15, random_state=42)

# experiment models
models = {
    "LinearRegression": LinearRegression(),
    "Ridge": Ridge(alpha=0.1),
    "Lasso": Lasso(alpha=0.1)}


performance = {
    "MAE" : [],
    "MSE" : [],
    "RMSE" : [],
    "R2" : []
}
np.random.seed(42)

for name, model in models.items():
    pipeline = Pipeline([
        ("normalization", (MinMaxScaler())),
        ("model", model)
    ])
    pipeline.fit(x_train, y_train)
    y_pred = pipeline.predict(x_test)
    performance["MAE"].append(mean_absolute_error(y_test, y_pred))
    performance["MSE"].append(mean_squared_error(y_test, y_pred))
    performance["RMSE"].append(root_mean_squared_error(y_test, y_pred))
    performance["R2"].append(r2_score(y_test, y_pred))
# format into pandas data frame
performance_df = pd.DataFrame(performance, index=models.keys())
print(performance_df)

                       MAE       MSE      RMSE        R2
LinearRegression  1.287522  1.965662  1.402021 -0.071127
Ridge             1.236588  1.782749  1.335196  0.028546
Lasso             1.101108  1.523620  1.234350  0.169750

In [20]:
# fill the missing values in tax_revenue_percentage with the best model (Lasso)
pipeline = Pipeline([
    ("normalization", (MinMaxScaler())),
    ("model", Lasso(alpha=0.1))
])
pipeline.fit(x_train, y_train)
x_imputed = df[df["tax_revenue_percentage(%)"].isna()][["gdp_growth(%)", "unemployment_rate(%)", 
        "inflation_rate(%)", "exchange_rate(IDR/US$)", "household_consumption(%)", "under_earning_percentage(%)"]]
y_pred_imputed = pipeline.predict(x_imputed)
df.loc[df["tax_revenue_percentage(%)"].isna(), "tax_revenue_percentage(%)"] = y_pred_imputed

In [21]:
df["tax_revenue_percentage(%)"][30:45]

30    11.477271
31    11.359080
32    11.017332
33    10.719321
34    10.124576
35     9.396496
36     9.256591
37     8.945110
38     8.446254
39     8.479459
40     8.480796
41     8.078380
42     7.336426
43     7.261091
Name: tax_revenue_percentage(%), dtype: float64

# Interpolate State Revenue Percentage

In [22]:
df["state_revenues_percentage(%)"] = df["state_revenues_percentage(%)"].interpolate(method="linear", order=2)

In [23]:
df["state_revenues_percentage(%)"][30:45]

30    15.108254
31    15.108254
32    15.108254
33    15.108254
34    15.108254
35    15.108254
36    15.108254
37    15.108254
38    15.108254
39    15.108254
40    15.108254
41    15.108254
42    15.108254
43    15.108254
Name: state_revenues_percentage(%), dtype: float64

# Impute Lending interest rate

In [24]:
df.isna().sum()

year                                   0
gdp_growth(%)                          0
gdp_growth_lag1(%)                     0
gdp_growth_lag2(%)                     0
household_consumption(%)               0
unemployment_rate(%)                   0
under_earning_percentage(%)            0
inflation_rate(%)                      0
lending_interest_rate(%)_x             6
fdi_net_flows(US$)                     0
tax_revenue_percentage(%)              0
state_revenues_percentage(%)           0
gross_capital_formation_growth(%)_x    0
import_of_goods_and_services(US$)      0
export_of_goods_and_services(US$)      0
gross_capital_formation_growth(%)_y    0
exchange_rate(IDR/US$)                 0
dtype: int64

In [25]:
df["lending_interest_rate(%)_x"].head(20)

0           NaN
1           NaN
2           NaN
3           NaN
4           NaN
5           NaN
6     21.504167
7     21.666667
8     22.097500
9     21.699167
10    20.825000
11    25.533333
12    24.033333
13    20.586667
14    17.760000
15    18.851667
16    19.217500
17    21.817500
18    32.154167
19    27.662500
Name: lending_interest_rate(%)_x, dtype: float64

In [26]:
# backfill
df["lending_interest_rate(%)_x"] = df["lending_interest_rate(%)_x"].fillna(method="bfill")
df["lending_interest_rate(%)_x"].head(20)

/var/folders/tk/mn4_r_cn03ndtjss8b670dfw0000gn/T/ipykernel_4406/2311269517.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["lending_interest_rate(%)_x"] = df["lending_interest_rate(%)_x"].fillna(method="bfill")

0     21.504167
1     21.504167
2     21.504167
3     21.504167
4     21.504167
5     21.504167
6     21.504167
7     21.666667
8     22.097500
9     21.699167
10    20.825000
11    25.533333
12    24.033333
13    20.586667
14    17.760000
15    18.851667
16    19.217500
17    21.817500
18    32.154167
19    27.662500
Name: lending_interest_rate(%)_x, dtype: float64

# Remove duplicate and format the label in a proper way

In [27]:
df.columns

Index(['year', 'gdp_growth(%)', 'gdp_growth_lag1(%)', 'gdp_growth_lag2(%)',
       'household_consumption(%)', 'unemployment_rate(%)',
       'under_earning_percentage(%)', 'inflation_rate(%)',
       'lending_interest_rate(%)_x', 'fdi_net_flows(US$)',
       'tax_revenue_percentage(%)', 'state_revenues_percentage(%)',
       'gross_capital_formation_growth(%)_x',
       'import_of_goods_and_services(US$)',
       'export_of_goods_and_services(US$)',
       'gross_capital_formation_growth(%)_y', 'exchange_rate(IDR/US$)'],
      dtype='object')

In [28]:
# change the column name of lending_interest_rate(%)_x to lending_interest_rate(%)
df.rename(columns={"lending_interest_rate(%)_x": "lending_interest_rate(%)"}, inplace=True)
# change the column name of lending_interest_rate(%)_y to lending_interest_rate(%)
df.rename(columns={"lending_interest_rate(%)_y": "lending_interest_rate(%)"}, inplace=True)
#change the column name of state_revenues_percentage(%) to state_revenues_percentage(%)
df.rename(columns={"state_revenues_percentage(%)": "state_revenues_percentage(%)"}, inplace=True)
#change the colun name of gross_capital_formation_growth(%)_x to gross_capital_formation_growth(%)
df.rename(columns={"gross_capital_formation_growth(%)_x": "gross_capital_formation_growth(%)"}, inplace=True)
# remove the column gross_capital_formation_growth(%)_y
df.drop(columns=["gross_capital_formation_growth(%)_y"], inplace=True)

In [29]:
df.columns

Index(['year', 'gdp_growth(%)', 'gdp_growth_lag1(%)', 'gdp_growth_lag2(%)',
       'household_consumption(%)', 'unemployment_rate(%)',
       'under_earning_percentage(%)', 'inflation_rate(%)',
       'lending_interest_rate(%)', 'fdi_net_flows(US$)',
       'tax_revenue_percentage(%)', 'state_revenues_percentage(%)',
       'gross_capital_formation_growth(%)',
       'import_of_goods_and_services(US$)',
       'export_of_goods_and_services(US$)', 'exchange_rate(IDR/US$)'],
      dtype='object')

In [30]:
df.columns.duplicated()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [31]:
# load the cleaned data into a new csv file
df.to_csv("cleaned_gdp_growth_data.csv", index=False)

# Create Lag-1 Data set

In [32]:
# Set 'year' as the index so it's preserved during shifts
df_indexed = df.set_index('year')

#Define your target (the original values we want to predict)
target_cols = ['gdp_growth(%)', 'gdp_growth_lag1(%)', 'gdp_growth_lag2(%)']
target = df_indexed[target_cols]

#Define your features and Shift them by 1
features = df_indexed.drop(columns=target_cols)
features_lag1 = features.shift(1)

# Combine them
df_lag1 = target.join(features_lag1).dropna()

In [33]:
df_lag1

,gdp_growth(%),gdp_growth_lag1(%),gdp_growth_lag2(%),household_consumption(%),unemployment_rate(%),under_earning_percentage(%),inflation_rate(%),lending_interest_rate(%),fdi_net_flows(US$),tax_revenue_percentage(%),state_revenues_percentage(%),gross_capital_formation_growth(%),import_of_goods_and_services(US$),export_of_goods_and_services(US$),exchange_rate(IDR/US$)
year,,,,,,,,,,,,,,,
1981,7.927157,9.880078,6.165775,70.834204,5.620902,89.164321,18.035422,21.504167,1.800000e+08,21.779838,22.897656,24.369558,1.607649e+10,2.208839e+10,626.994000
1982,2.246445,7.927157,9.880078,76.531919,5.620827,88.921829,12.265908,21.504167,1.330000e+08,21.946434,25.474300,12.398103,2.184722e+10,2.362907e+10,631.756667
1983,4.192967,2.246445,7.927157,81.334706,5.504006,75.150527,9.445425,21.504167,2.250000e+08,20.056144,21.489923,5.647824,2.370914e+10,2.017659e+10,661.420750
1984,6.975528,4.192967,2.246445,71.666649,5.565429,67.419547,11.799738,21.504167,2.920000e+08,18.822865,21.046818,627.499564,2.335427e+10,2.248829e+10,909.264833
1985,2.462144,6.975528,4.192967,72.352702,5.744096,86.200000,10.455039,21.504167,2.220000e+08,17.484389,21.508291,52.568955,1.934295e+10,2.317777e+10,1025.944833
1986,5.875045,2.462144,6.975528,72.424958,5.682875,71.527427,4.724535,21.504167,3.100000e+08,18.750897,21.481026,46.486894,1.786022e+10,2.027985e+10,1110.580000
1987,4.925927,5.875045,2.462144,75.208760,5.595359,60.273201,5.822666,21.504167,2.580000e+08,14.620770,20.794591,-3.995642,1.640173e+10,1.638707e+10,1282.560000
1988,5.780498,4.925927,5.875045,71.411564,5.737312,86.800000,9.278654,21.666667,3.850000e+08,15.083695,19.853882,-18.896794,1.700630e+10,1.866107e+10,1643.848333
1989,7.456587,5.780498,4.925927,72.114454,5.629971,67.660828,8.045357,22.097500,5.760000e+08,15.083938,16.950870,-71.621388,1.872552e+10,2.111016e+10,1685.704167
1990,7.242132,7.456587,5.780498,69.343427,5.659822,66.733250,6.415541,21.699167,6.820000e+08,15.957202,17.401712,22.952061,2.171847e+10,2.464007e+10,1770.059167
1991,6.911983,7.242132,7.456587,73.024205,5.632945,78.600000,7.819198,20.825000,1.093000e+09,19.137084,20.228306,103.268736,2.715728e+10,2.898253e+10,1842.813333
1992,6.497507,6.911983,7.242132,73.359707,2.617000,69.433190,9.419068,25.533333,1.482000e+09,17.189697,18.648038,-33.202098,3.089119e+10,3.306381e+10,1950.317500
1993,6.496408,6.497507,6.911983,72.356220,2.734000,65.358433,7.523510,24.033333,1.777000e+09,17.122953,19.487503,13.744395,3.472088e+10,3.880173e+10,2029.920833
1994,7.539971,6.496408,6.497507,67.535307,2.782000,78.000000,9.671911,20.586667,2.004000e+09,14.356420,17.077663,38.450762,3.755594e+10,4.227440e+10,2087.103867
1995,8.220007,7.539971,6.496408,67.796950,4.366000,65.597060,8.531998,17.760000,2.109000e+09,15.948419,18.155527,36.400063,4.486988e+10,4.689663e+10,2160.753675
1996,7.818187,8.220007,7.539971,69.406120,4.611000,69.515793,9.420303,18.851667,4.346000e+09,14.964772,17.691860,7.800788,5.588228e+10,5.318531e+10,2248.607975
1997,4.699879,7.818187,8.220007,69.924141,4.861000,68.100000,7.973281,19.217500,6.194000e+09,14.234802,16.953516,-52.080132,6.011698e+10,5.871720e+10,2342.296292
1998,-13.126725,4.699879,7.818187,68.524069,4.684000,58.154335,6.226152,21.817500,4.677000e+09,16.011848,18.137719,-25.772651,6.070015e+10,6.010604e+10,2909.380000
1999,0.791126,-13.126725,4.699879,73.474960,5.459000,82.800000,58.451041,32.154167,-2.408000e+08,15.027588,16.466714,-164.509353,4.124971e+10,5.055573e+10,10013.622500
2000,4.920068,0.791126,-13.126725,80.548254,6.358000,66.200000,20.477832,27.662500,-1.865621e+09,16.315836,18.059979,85.726670,3.840207e+10,4.972026e+10,7855.150000
2001,3.643466,4.920068,0.791126,68.182366,6.077000,65.700000,3.688620,18.455000,-4.550355e+09,13.947010,18.379341,49.332978,5.026469e+10,6.762117e+10,8421.775000
2002,4.499475,3.643466,4.920068,70.039221,6.082000,62.300000,11.500116,18.547500,-2.977392e+09,11.578185,18.698703,29.105461,4.935520e+10,6.262588e+10,10260.850000
2003,4.780369,4.499475,3.643466,74.879695,6.604000,46.800000,11.900120,18.945000,1.450855e+08,11.826960,17.444367,-79.354325,5.163844e+10,6.395680e+10,9311.191667
2004,5.030874,4.780369,4.499475,76.267506,6.657000,45.500000,6.757313,16.935000,-5.969238e+08,12.385532,17.323473,435.616000,5.432362e+10,7.155314e+10,8577.133333
2005,5.692571,5.030874,4.780369,75.090350,7.303000,45.400000,6.064062,14.124167,1.896083e+09,12.330768,18.365509,-53.716777,7.074469e+10,8.274435e+10,8938.850000
2006,5.500952,5.692571,5.030874,72.471998,7.945000,41.100000,10.453200,14.050833,8.336257e+09,12.575730,18.721093,41.226522,8.553380e+10,9.738763e+10,9704.741667
2007,6.345022,5.500952,5.692571,71.296226,7.551000,46.800000,13.108671,15.979167,4.914201e+09,12.820693,19.076677,-17.656484,9.341175e+10,1.131434e+11,9159.316667
2008,6.013704,6.345022,5.500952,71.889159,8.060000,41.100000,6.406561,13.861667,6.928480e+09,13.065655,19.432260,-137.635084,1.097551e+11,1.272261e+11,9141.000000
2009,4.628871,6.013704,6.345022,69.045034,7.208000,38.000000,10.226666,13.598333,9.318454e+09,13.310618,19.787844,-17.939593,1.467066e+11,1.520904e+11,9698.962500
2010,6.223854,4.628871,6.013704,68.291934,6.106000,37.900000,4.386413,14.498333,4.877369e+09,11.057787,15.108254,67.389372,1.152165e+11,1.303578e+11,10389.937500
2011,6.169784,6.223854,4.628871,65.223091,5.614000,34.100000,5.134206,13.251667,1.529201e+10,11.477271,15.108254,-6.063093,1.691580e+11,1.834806e+11,9090.433333
2012,6.030051,6.169784,6.223854,64.482034,5.153000,31.200000,5.356048,12.403333,2.056494e+10,11.359080,15.108254,7.870459,2.129969e+11,2.350951e+11,8770.433333
2013,5.557264,6.030051,6.169784,65.638035,4.468000,26.600000,4.279514,11.795000,2.120078e+10,11.017332,15.108254,10.981235,2.293621e+11,2.257444e+11,9386.629167
2014,5.006668,5.557264,6.030051,66.347182,4.336000,27.200000,6.412495,11.657500,2.328174e+10,10.719321,15.108254,2.846751,2.255194e+11,2.183084e+11,10461.240000
2015,4.876322,5.006668,5.557264,66.564142,4.049000,25.700000,6.394929,12.605000,2.512073e+10,10.124576,15.108254,5.657952,2.174852e+11,2.108201e+11,11865.211296
2016,5.033069,4.876322,5.006668,67.199432,4.514000,21.600000,6.363121,12.662500,1.977913e+10,9.396496,15.108254,3.002346,1.788637e+11,1.821583e+11,13389.412937
2017,5.069786,5.033069,4.876322,67.354611,4.301000,18.000000,3.525805,11.888333,4.541714e+09,9.256591,15.108254,4.985806,1.708350e+11,1.778860e+11,13308.326802
2018,5.174292,5.069786,5.033069,66.396144,3.783000,14.800000,3.808799,11.073333,2.051031e+10,8.945110,15.108254,5.690161,1.947773e+11,2.049245e+11,13380.833879
2019,5.019288,5.174292,5.069786,66.001127,4.387000,12.500000,3.198348,10.536667,1.890983e+10,8.446254,15.108254,8.523941,2.300456e+11,2.189056e+11,14236.938773
2020,-2.065512,5.019288,5.174292,66.738936,3.590000,10.800000,3.030585,10.365833,2.499355e+10,8.479459,15.108254,2.359847,2.130346e+11,2.080578e+11,14147.671361
2021,3.702886,-2.065512,5.019288,68.589643,4.255000,9.800000,1.919835,9.544167,1.917508e+10,8.480796,15.108254,-6.897226,1.656468e+11,1.835466e+11,14582.203468
2022,5.307197,3.702886,-2.065512,64.875755,3.827000,8.600000,1.560079,8.922500,2.121308e+10,8.078380,15.108254,4.074672,2.229238e+11,2.541095e+11,14308.143901
2023,5.049023,5.307197,3.702886,60.734725,3.462000,7.900000,4.209465,8.520000,2.470203e+10,7.336426,15.108254,4.025415,2.765068e+11,3.232182e+11,14849.853936

In [34]:
df_lag1.to_csv("cleaned_gdp_growth_data_lag1.csv", index=False)

In [35]:
# change the name
labels = df_lag1.columns[3:]

for label in labels:
    df_lag1.rename(columns={label: label + "_lag1"}, inplace=True)

In [36]:
df_lag1

,gdp_growth(%),gdp_growth_lag1(%),gdp_growth_lag2(%),household_consumption(%)_lag1,unemployment_rate(%)_lag1,under_earning_percentage(%)_lag1,inflation_rate(%)_lag1,lending_interest_rate(%)_lag1,fdi_net_flows(US$)_lag1,tax_revenue_percentage(%)_lag1,state_revenues_percentage(%)_lag1,gross_capital_formation_growth(%)_lag1,import_of_goods_and_services(US$)_lag1,export_of_goods_and_services(US$)_lag1,exchange_rate(IDR/US$)_lag1
year,,,,,,,,,,,,,,,
1981,7.927157,9.880078,6.165775,70.834204,5.620902,89.164321,18.035422,21.504167,1.800000e+08,21.779838,22.897656,24.369558,1.607649e+10,2.208839e+10,626.994000
1982,2.246445,7.927157,9.880078,76.531919,5.620827,88.921829,12.265908,21.504167,1.330000e+08,21.946434,25.474300,12.398103,2.184722e+10,2.362907e+10,631.756667
1983,4.192967,2.246445,7.927157,81.334706,5.504006,75.150527,9.445425,21.504167,2.250000e+08,20.056144,21.489923,5.647824,2.370914e+10,2.017659e+10,661.420750
1984,6.975528,4.192967,2.246445,71.666649,5.565429,67.419547,11.799738,21.504167,2.920000e+08,18.822865,21.046818,627.499564,2.335427e+10,2.248829e+10,909.264833
1985,2.462144,6.975528,4.192967,72.352702,5.744096,86.200000,10.455039,21.504167,2.220000e+08,17.484389,21.508291,52.568955,1.934295e+10,2.317777e+10,1025.944833
1986,5.875045,2.462144,6.975528,72.424958,5.682875,71.527427,4.724535,21.504167,3.100000e+08,18.750897,21.481026,46.486894,1.786022e+10,2.027985e+10,1110.580000
1987,4.925927,5.875045,2.462144,75.208760,5.595359,60.273201,5.822666,21.504167,2.580000e+08,14.620770,20.794591,-3.995642,1.640173e+10,1.638707e+10,1282.560000
1988,5.780498,4.925927,5.875045,71.411564,5.737312,86.800000,9.278654,21.666667,3.850000e+08,15.083695,19.853882,-18.896794,1.700630e+10,1.866107e+10,1643.848333
1989,7.456587,5.780498,4.925927,72.114454,5.629971,67.660828,8.045357,22.097500,5.760000e+08,15.083938,16.950870,-71.621388,1.872552e+10,2.111016e+10,1685.704167
1990,7.242132,7.456587,5.780498,69.343427,5.659822,66.733250,6.415541,21.699167,6.820000e+08,15.957202,17.401712,22.952061,2.171847e+10,2.464007e+10,1770.059167
1991,6.911983,7.242132,7.456587,73.024205,5.632945,78.600000,7.819198,20.825000,1.093000e+09,19.137084,20.228306,103.268736,2.715728e+10,2.898253e+10,1842.813333
1992,6.497507,6.911983,7.242132,73.359707,2.617000,69.433190,9.419068,25.533333,1.482000e+09,17.189697,18.648038,-33.202098,3.089119e+10,3.306381e+10,1950.317500
1993,6.496408,6.497507,6.911983,72.356220,2.734000,65.358433,7.523510,24.033333,1.777000e+09,17.122953,19.487503,13.744395,3.472088e+10,3.880173e+10,2029.920833
1994,7.539971,6.496408,6.497507,67.535307,2.782000,78.000000,9.671911,20.586667,2.004000e+09,14.356420,17.077663,38.450762,3.755594e+10,4.227440e+10,2087.103867
1995,8.220007,7.539971,6.496408,67.796950,4.366000,65.597060,8.531998,17.760000,2.109000e+09,15.948419,18.155527,36.400063,4.486988e+10,4.689663e+10,2160.753675
1996,7.818187,8.220007,7.539971,69.406120,4.611000,69.515793,9.420303,18.851667,4.346000e+09,14.964772,17.691860,7.800788,5.588228e+10,5.318531e+10,2248.607975
1997,4.699879,7.818187,8.220007,69.924141,4.861000,68.100000,7.973281,19.217500,6.194000e+09,14.234802,16.953516,-52.080132,6.011698e+10,5.871720e+10,2342.296292
1998,-13.126725,4.699879,7.818187,68.524069,4.684000,58.154335,6.226152,21.817500,4.677000e+09,16.011848,18.137719,-25.772651,6.070015e+10,6.010604e+10,2909.380000
1999,0.791126,-13.126725,4.699879,73.474960,5.459000,82.800000,58.451041,32.154167,-2.408000e+08,15.027588,16.466714,-164.509353,4.124971e+10,5.055573e+10,10013.622500
2000,4.920068,0.791126,-13.126725,80.548254,6.358000,66.200000,20.477832,27.662500,-1.865621e+09,16.315836,18.059979,85.726670,3.840207e+10,4.972026e+10,7855.150000
2001,3.643466,4.920068,0.791126,68.182366,6.077000,65.700000,3.688620,18.455000,-4.550355e+09,13.947010,18.379341,49.332978,5.026469e+10,6.762117e+10,8421.775000
2002,4.499475,3.643466,4.920068,70.039221,6.082000,62.300000,11.500116,18.547500,-2.977392e+09,11.578185,18.698703,29.105461,4.935520e+10,6.262588e+10,10260.850000
2003,4.780369,4.499475,3.643466,74.879695,6.604000,46.800000,11.900120,18.945000,1.450855e+08,11.826960,17.444367,-79.354325,5.163844e+10,6.395680e+10,9311.191667
2004,5.030874,4.780369,4.499475,76.267506,6.657000,45.500000,6.757313,16.935000,-5.969238e+08,12.385532,17.323473,435.616000,5.432362e+10,7.155314e+10,8577.133333
2005,5.692571,5.030874,4.780369,75.090350,7.303000,45.400000,6.064062,14.124167,1.896083e+09,12.330768,18.365509,-53.716777,7.074469e+10,8.274435e+10,8938.850000
2006,5.500952,5.692571,5.030874,72.471998,7.945000,41.100000,10.453200,14.050833,8.336257e+09,12.575730,18.721093,41.226522,8.553380e+10,9.738763e+10,9704.741667
2007,6.345022,5.500952,5.692571,71.296226,7.551000,46.800000,13.108671,15.979167,4.914201e+09,12.820693,19.076677,-17.656484,9.341175e+10,1.131434e+11,9159.316667
2008,6.013704,6.345022,5.500952,71.889159,8.060000,41.100000,6.406561,13.861667,6.928480e+09,13.065655,19.432260,-137.635084,1.097551e+11,1.272261e+11,9141.000000
2009,4.628871,6.013704,6.345022,69.045034,7.208000,38.000000,10.226666,13.598333,9.318454e+09,13.310618,19.787844,-17.939593,1.467066e+11,1.520904e+11,9698.962500
2010,6.223854,4.628871,6.013704,68.291934,6.106000,37.900000,4.386413,14.498333,4.877369e+09,11.057787,15.108254,67.389372,1.152165e+11,1.303578e+11,10389.937500
2011,6.169784,6.223854,4.628871,65.223091,5.614000,34.100000,5.134206,13.251667,1.529201e+10,11.477271,15.108254,-6.063093,1.691580e+11,1.834806e+11,9090.433333
2012,6.030051,6.169784,6.223854,64.482034,5.153000,31.200000,5.356048,12.403333,2.056494e+10,11.359080,15.108254,7.870459,2.129969e+11,2.350951e+11,8770.433333
2013,5.557264,6.030051,6.169784,65.638035,4.468000,26.600000,4.279514,11.795000,2.120078e+10,11.017332,15.108254,10.981235,2.293621e+11,2.257444e+11,9386.629167
2014,5.006668,5.557264,6.030051,66.347182,4.336000,27.200000,6.412495,11.657500,2.328174e+10,10.719321,15.108254,2.846751,2.255194e+11,2.183084e+11,10461.240000
2015,4.876322,5.006668,5.557264,66.564142,4.049000,25.700000,6.394929,12.605000,2.512073e+10,10.124576,15.108254,5.657952,2.174852e+11,2.108201e+11,11865.211296
2016,5.033069,4.876322,5.006668,67.199432,4.514000,21.600000,6.363121,12.662500,1.977913e+10,9.396496,15.108254,3.002346,1.788637e+11,1.821583e+11,13389.412937
2017,5.069786,5.033069,4.876322,67.354611,4.301000,18.000000,3.525805,11.888333,4.541714e+09,9.256591,15.108254,4.985806,1.708350e+11,1.778860e+11,13308.326802
2018,5.174292,5.069786,5.033069,66.396144,3.783000,14.800000,3.808799,11.073333,2.051031e+10,8.945110,15.108254,5.690161,1.947773e+11,2.049245e+11,13380.833879
2019,5.019288,5.174292,5.069786,66.001127,4.387000,12.500000,3.198348,10.536667,1.890983e+10,8.446254,15.108254,8.523941,2.300456e+11,2.189056e+11,14236.938773
2020,-2.065512,5.019288,5.174292,66.738936,3.590000,10.800000,3.030585,10.365833,2.499355e+10,8.479459,15.108254,2.359847,2.130346e+11,2.080578e+11,14147.671361
2021,3.702886,-2.065512,5.019288,68.589643,4.255000,9.800000,1.919835,9.544167,1.917508e+10,8.480796,15.108254,-6.897226,1.656468e+11,1.835466e+11,14582.203468
2022,5.307197,3.702886,-2.065512,64.875755,3.827000,8.600000,1.560079,8.922500,2.121308e+10,8.078380,15.108254,4.074672,2.229238e+11,2.541095e+11,14308.143901
2023,5.049023,5.307197,3.702886,60.734725,3.462000,7.900000,4.209465,8.520000,2.470203e+10,7.336426,15.108254,4.025415,2.765068e+11,3.232182e+11,14849.853936

In [40]:
df_lag1.to_csv("cleaned_gdp_growth_lag1.csv", index=True)